// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm1hosYBVxmR4kz9qXrwqDnrO9fJt9DbU',
    appId: '1:25938226207:web:85e8f7d7192d559fdb792a',
    messagingSenderId: '25938226207',
    projectId: 'cgv-clne',
    authDomain: 'cgv-clne.firebaseapp.com',
    storageBucket: 'cgv-clne.appspot.com',
    measurementId: 'G-Z1N45YL51S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLK4wH2qRLZ6apvGIa4FqfFex89bOBC9U',
    appId: '1:25938226207:android:00bb712e5aef00b6db792a',
    messagingSenderId: '25938226207',
    projectId: 'cgv-clne',
    storageBucket: 'cgv-clne.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwNolJApR7-Drmmg3kb7lQSxhqw_Uv6f4',
    appId: '1:25938226207:ios:94586fda6ad1a20adb792a',
    messagingSenderId: '25938226207',
    projectId: 'cgv-clne',
    storageBucket: 'cgv-clne.appspot.com',
    iosBundleId: 'com.example.cgvClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwNolJApR7-Drmmg3kb7lQSxhqw_Uv6f4',
    appId: '1:25938226207:ios:370b3f217a4e0be3db792a',
    messagingSenderId: '25938226207',
    projectId: 'cgv-clne',
    storageBucket: 'cgv-clne.appspot.com',
    iosBundleId: 'com.example.cgvClone.RunnerTests',
  );
}
