// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW3cb0wj61q1pZhwgNv_V6n-CpwCXPXcU',
    appId: '1:28758594488:web:bd48a6867c4f64c650354d',
    messagingSenderId: '28758594488',
    projectId: 'login-5405b',
    authDomain: 'login-5405b.firebaseapp.com',
    storageBucket: 'login-5405b.appspot.com',
    measurementId: 'G-YKFCY5G9QV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0i5_Dk5NMsHL6gLsJD2_hTuIcSFSsJrA',
    appId: '1:28758594488:android:7c88feb2bfb2385d50354d',
    messagingSenderId: '28758594488',
    projectId: 'login-5405b',
    storageBucket: 'login-5405b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANRIJ7XWpb_mGbuBSwlxslAXm5iq9N0OA',
    appId: '1:28758594488:ios:0f8004c42ed5807a50354d',
    messagingSenderId: '28758594488',
    projectId: 'login-5405b',
    storageBucket: 'login-5405b.appspot.com',
    iosBundleId: 'com.example.cgvClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANRIJ7XWpb_mGbuBSwlxslAXm5iq9N0OA',
    appId: '1:28758594488:ios:e3785186b0dbc11e50354d',
    messagingSenderId: '28758594488',
    projectId: 'login-5405b',
    storageBucket: 'login-5405b.appspot.com',
    iosBundleId: 'com.example.cgvClone.RunnerTests',
  );
}
