// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9xtmqYtjFRyWfFeH1__VitKqiUyLFl8M',
    appId: '1:274426896884:web:83e4e2f3f06983d3a719a1',
    messagingSenderId: '274426896884',
    projectId: 'ascamp-d4e76',
    authDomain: 'ascamp-d4e76.firebaseapp.com',
    storageBucket: 'ascamp-d4e76.appspot.com',
    measurementId: 'G-GWF4EQRZZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5OVm12JCTU1prgVAeXKYI_jlQzsWtUkE',
    appId: '1:274426896884:android:a98c36c1bdde2a50a719a1',
    messagingSenderId: '274426896884',
    projectId: 'ascamp-d4e76',
    storageBucket: 'ascamp-d4e76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOl_uP3DhyKYTHm9vJEwNsQ2PBsF3ejmA',
    appId: '1:274426896884:ios:f5132aa139a354e5a719a1',
    messagingSenderId: '274426896884',
    projectId: 'ascamp-d4e76',
    storageBucket: 'ascamp-d4e76.appspot.com',
    iosBundleId: 'com.example.asTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOl_uP3DhyKYTHm9vJEwNsQ2PBsF3ejmA',
    appId: '1:274426896884:ios:4e193b09fdd2a6c0a719a1',
    messagingSenderId: '274426896884',
    projectId: 'ascamp-d4e76',
    storageBucket: 'ascamp-d4e76.appspot.com',
    iosBundleId: 'com.example.asTest.RunnerTests',
  );
}
